//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AgentNetworkManagement.Web.com.smslive247.www1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISMSSiteAdmin", Namespace="http://tempuri.org/")]
    public partial class SMSSiteAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewSiteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSiteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSiteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSiteUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback FlashSiteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePwdOperationCompleted;
        
        private System.Threading.SendOrPostCallback RechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContactsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SMSSiteAdmin() {
            this.Url = global::AgentNetworkManagement.Web.Properties.Settings.Default.AgentNetworkManagement_Web_com_smslive247_www1_SMSSiteAdmin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewSiteUserCompletedEventHandler NewSiteUserCompleted;
        
        /// <remarks/>
        public event UpdateSiteUserCompletedEventHandler UpdateSiteUserCompleted;
        
        /// <remarks/>
        public event DeleteSiteUserCompletedEventHandler DeleteSiteUserCompleted;
        
        /// <remarks/>
        public event GetAllSiteUsersCompletedEventHandler GetAllSiteUsersCompleted;
        
        /// <remarks/>
        public event FlashSiteUserCompletedEventHandler FlashSiteUserCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event ChangePwdCompletedEventHandler ChangePwdCompleted;
        
        /// <remarks/>
        public event RechargeCompletedEventHandler RechargeCompleted;
        
        /// <remarks/>
        public event UpdateAccountInfoCompletedEventHandler UpdateAccountInfoCompleted;
        
        /// <remarks/>
        public event GetAccountInfoCompletedEventHandler GetAccountInfoCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event GetMessagesCompletedEventHandler GetMessagesCompleted;
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event InsertContactCompletedEventHandler InsertContactCompleted;
        
        /// <remarks/>
        public event UpdateContactCompletedEventHandler UpdateContactCompleted;
        
        /// <remarks/>
        public event DeleteContactCompletedEventHandler DeleteContactCompleted;
        
        /// <remarks/>
        public event GetContactsCompletedEventHandler GetContactsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/NewSiteUser", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo NewSiteUser(string site_token, SMSSiteUserInfo User) {
            object[] results = this.Invoke("NewSiteUser", new object[] {
                        site_token,
                        User});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void NewSiteUserAsync(string site_token, SMSSiteUserInfo User) {
            this.NewSiteUserAsync(site_token, User, null);
        }
        
        /// <remarks/>
        public void NewSiteUserAsync(string site_token, SMSSiteUserInfo User, object userState) {
            if ((this.NewSiteUserOperationCompleted == null)) {
                this.NewSiteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewSiteUserOperationCompleted);
            }
            this.InvokeAsync("NewSiteUser", new object[] {
                        site_token,
                        User}, this.NewSiteUserOperationCompleted, userState);
        }
        
        private void OnNewSiteUserOperationCompleted(object arg) {
            if ((this.NewSiteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewSiteUserCompleted(this, new NewSiteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/UpdateSiteUser", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo UpdateSiteUser(string site_token, SMSSiteUserInfo User) {
            object[] results = this.Invoke("UpdateSiteUser", new object[] {
                        site_token,
                        User});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSiteUserAsync(string site_token, SMSSiteUserInfo User) {
            this.UpdateSiteUserAsync(site_token, User, null);
        }
        
        /// <remarks/>
        public void UpdateSiteUserAsync(string site_token, SMSSiteUserInfo User, object userState) {
            if ((this.UpdateSiteUserOperationCompleted == null)) {
                this.UpdateSiteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSiteUserOperationCompleted);
            }
            this.InvokeAsync("UpdateSiteUser", new object[] {
                        site_token,
                        User}, this.UpdateSiteUserOperationCompleted, userState);
        }
        
        private void OnUpdateSiteUserOperationCompleted(object arg) {
            if ((this.UpdateSiteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSiteUserCompleted(this, new UpdateSiteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/DeleteSiteUser", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo DeleteSiteUser(string site_token, string Username) {
            object[] results = this.Invoke("DeleteSiteUser", new object[] {
                        site_token,
                        Username});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSiteUserAsync(string site_token, string Username) {
            this.DeleteSiteUserAsync(site_token, Username, null);
        }
        
        /// <remarks/>
        public void DeleteSiteUserAsync(string site_token, string Username, object userState) {
            if ((this.DeleteSiteUserOperationCompleted == null)) {
                this.DeleteSiteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSiteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteSiteUser", new object[] {
                        site_token,
                        Username}, this.DeleteSiteUserOperationCompleted, userState);
        }
        
        private void OnDeleteSiteUserOperationCompleted(object arg) {
            if ((this.DeleteSiteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSiteUserCompleted(this, new DeleteSiteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/GetAllSiteUsers", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMSSiteUserInfo[] GetAllSiteUsers(string site_token) {
            object[] results = this.Invoke("GetAllSiteUsers", new object[] {
                        site_token});
            return ((SMSSiteUserInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSiteUsersAsync(string site_token) {
            this.GetAllSiteUsersAsync(site_token, null);
        }
        
        /// <remarks/>
        public void GetAllSiteUsersAsync(string site_token, object userState) {
            if ((this.GetAllSiteUsersOperationCompleted == null)) {
                this.GetAllSiteUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSiteUsersOperationCompleted);
            }
            this.InvokeAsync("GetAllSiteUsers", new object[] {
                        site_token}, this.GetAllSiteUsersOperationCompleted, userState);
        }
        
        private void OnGetAllSiteUsersOperationCompleted(object arg) {
            if ((this.GetAllSiteUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSiteUsersCompleted(this, new GetAllSiteUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/FlashSiteUser", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo FlashSiteUser(string site_token, string RecieverName, int SMS_Count) {
            object[] results = this.Invoke("FlashSiteUser", new object[] {
                        site_token,
                        RecieverName,
                        SMS_Count});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void FlashSiteUserAsync(string site_token, string RecieverName, int SMS_Count) {
            this.FlashSiteUserAsync(site_token, RecieverName, SMS_Count, null);
        }
        
        /// <remarks/>
        public void FlashSiteUserAsync(string site_token, string RecieverName, int SMS_Count, object userState) {
            if ((this.FlashSiteUserOperationCompleted == null)) {
                this.FlashSiteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFlashSiteUserOperationCompleted);
            }
            this.InvokeAsync("FlashSiteUser", new object[] {
                        site_token,
                        RecieverName,
                        SMS_Count}, this.FlashSiteUserOperationCompleted, userState);
        }
        
        private void OnFlashSiteUserOperationCompleted(object arg) {
            if ((this.FlashSiteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FlashSiteUserCompleted(this, new FlashSiteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/Login", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo Login(string site_id, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        site_id,
                        Password});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string site_id, string Password) {
            this.LoginAsync(site_id, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string site_id, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        site_id,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/ChangePwd", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo ChangePwd(string site_token, string OldPassword, string NewPassword) {
            object[] results = this.Invoke("ChangePwd", new object[] {
                        site_token,
                        OldPassword,
                        NewPassword});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string site_token, string OldPassword, string NewPassword) {
            this.ChangePwdAsync(site_token, OldPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void ChangePwdAsync(string site_token, string OldPassword, string NewPassword, object userState) {
            if ((this.ChangePwdOperationCompleted == null)) {
                this.ChangePwdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePwdOperationCompleted);
            }
            this.InvokeAsync("ChangePwd", new object[] {
                        site_token,
                        OldPassword,
                        NewPassword}, this.ChangePwdOperationCompleted, userState);
        }
        
        private void OnChangePwdOperationCompleted(object arg) {
            if ((this.ChangePwdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePwdCompleted(this, new ChangePwdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/Recharge", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo Recharge(string site_token, string str16DigitCode) {
            object[] results = this.Invoke("Recharge", new object[] {
                        site_token,
                        str16DigitCode});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void RechargeAsync(string site_token, string str16DigitCode) {
            this.RechargeAsync(site_token, str16DigitCode, null);
        }
        
        /// <remarks/>
        public void RechargeAsync(string site_token, string str16DigitCode, object userState) {
            if ((this.RechargeOperationCompleted == null)) {
                this.RechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRechargeOperationCompleted);
            }
            this.InvokeAsync("Recharge", new object[] {
                        site_token,
                        str16DigitCode}, this.RechargeOperationCompleted, userState);
        }
        
        private void OnRechargeOperationCompleted(object arg) {
            if ((this.RechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RechargeCompleted(this, new RechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/UpdateAccountInfo", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo UpdateAccountInfo(string site_token, SMSSiteInfo NewInfo) {
            object[] results = this.Invoke("UpdateAccountInfo", new object[] {
                        site_token,
                        NewInfo});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAccountInfoAsync(string site_token, SMSSiteInfo NewInfo) {
            this.UpdateAccountInfoAsync(site_token, NewInfo, null);
        }
        
        /// <remarks/>
        public void UpdateAccountInfoAsync(string site_token, SMSSiteInfo NewInfo, object userState) {
            if ((this.UpdateAccountInfoOperationCompleted == null)) {
                this.UpdateAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAccountInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateAccountInfo", new object[] {
                        site_token,
                        NewInfo}, this.UpdateAccountInfoOperationCompleted, userState);
        }
        
        private void OnUpdateAccountInfoOperationCompleted(object arg) {
            if ((this.UpdateAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAccountInfoCompleted(this, new UpdateAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/GetAccountInfo", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SMSSiteInfo GetAccountInfo(string site_token) {
            object[] results = this.Invoke("GetAccountInfo", new object[] {
                        site_token});
            return ((SMSSiteInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string site_token) {
            this.GetAccountInfoAsync(site_token, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string site_token, object userState) {
            if ((this.GetAccountInfoOperationCompleted == null)) {
                this.GetAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfo", new object[] {
                        site_token}, this.GetAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoOperationCompleted(object arg) {
            if ((this.GetAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoCompleted(this, new GetAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/SendSMS", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo SendSMS(string site_token, MessageInfo NewSMS) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        site_token,
                        NewSMS});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(string site_token, MessageInfo NewSMS) {
            this.SendSMSAsync(site_token, NewSMS, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(string site_token, MessageInfo NewSMS, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        site_token,
                        NewSMS}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/GetMessages", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SentMessageInfo[] GetMessages(string site_token, System.DateTime from_date, System.DateTime to_date) {
            object[] results = this.Invoke("GetMessages", new object[] {
                        site_token,
                        from_date,
                        to_date});
            return ((SentMessageInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMessagesAsync(string site_token, System.DateTime from_date, System.DateTime to_date) {
            this.GetMessagesAsync(site_token, from_date, to_date, null);
        }
        
        /// <remarks/>
        public void GetMessagesAsync(string site_token, System.DateTime from_date, System.DateTime to_date, object userState) {
            if ((this.GetMessagesOperationCompleted == null)) {
                this.GetMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessagesOperationCompleted);
            }
            this.InvokeAsync("GetMessages", new object[] {
                        site_token,
                        from_date,
                        to_date}, this.GetMessagesOperationCompleted, userState);
        }
        
        private void OnGetMessagesOperationCompleted(object arg) {
            if ((this.GetMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessagesCompleted(this, new GetMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/DeleteMessage", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo DeleteMessage(string site_token, string MessageID) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        site_token,
                        MessageID});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(string site_token, string MessageID) {
            this.DeleteMessageAsync(site_token, MessageID, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(string site_token, string MessageID, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        site_token,
                        MessageID}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/InsertContact", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo InsertContact(string site_token, ContactInfo myContact) {
            object[] results = this.Invoke("InsertContact", new object[] {
                        site_token,
                        myContact});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void InsertContactAsync(string site_token, ContactInfo myContact) {
            this.InsertContactAsync(site_token, myContact, null);
        }
        
        /// <remarks/>
        public void InsertContactAsync(string site_token, ContactInfo myContact, object userState) {
            if ((this.InsertContactOperationCompleted == null)) {
                this.InsertContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertContactOperationCompleted);
            }
            this.InvokeAsync("InsertContact", new object[] {
                        site_token,
                        myContact}, this.InsertContactOperationCompleted, userState);
        }
        
        private void OnInsertContactOperationCompleted(object arg) {
            if ((this.InsertContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertContactCompleted(this, new InsertContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/UpdateContact", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo UpdateContact(string site_token, ContactInfo myContact) {
            object[] results = this.Invoke("UpdateContact", new object[] {
                        site_token,
                        myContact});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateContactAsync(string site_token, ContactInfo myContact) {
            this.UpdateContactAsync(site_token, myContact, null);
        }
        
        /// <remarks/>
        public void UpdateContactAsync(string site_token, ContactInfo myContact, object userState) {
            if ((this.UpdateContactOperationCompleted == null)) {
                this.UpdateContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateContactOperationCompleted);
            }
            this.InvokeAsync("UpdateContact", new object[] {
                        site_token,
                        myContact}, this.UpdateContactOperationCompleted, userState);
        }
        
        private void OnUpdateContactOperationCompleted(object arg) {
            if ((this.UpdateContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateContactCompleted(this, new UpdateContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/DeleteContact", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseInfo DeleteContact(string site_token, string MobileNo) {
            object[] results = this.Invoke("DeleteContact", new object[] {
                        site_token,
                        MobileNo});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteContactAsync(string site_token, string MobileNo) {
            this.DeleteContactAsync(site_token, MobileNo, null);
        }
        
        /// <remarks/>
        public void DeleteContactAsync(string site_token, string MobileNo, object userState) {
            if ((this.DeleteContactOperationCompleted == null)) {
                this.DeleteContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteContactOperationCompleted);
            }
            this.InvokeAsync("DeleteContact", new object[] {
                        site_token,
                        MobileNo}, this.DeleteContactOperationCompleted, userState);
        }
        
        private void OnDeleteContactOperationCompleted(object arg) {
            if ((this.DeleteContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteContactCompleted(this, new DeleteContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smslive247.com/bulksms/service/GetContacts", RequestNamespace="http://smslive247.com/bulksms/service", ResponseNamespace="http://smslive247.com/bulksms/service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ContactInfo[] GetContacts(string site_token) {
            object[] results = this.Invoke("GetContacts", new object[] {
                        site_token});
            return ((ContactInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetContactsAsync(string site_token) {
            this.GetContactsAsync(site_token, null);
        }
        
        /// <remarks/>
        public void GetContactsAsync(string site_token, object userState) {
            if ((this.GetContactsOperationCompleted == null)) {
                this.GetContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactsOperationCompleted);
            }
            this.InvokeAsync("GetContacts", new object[] {
                        site_token}, this.GetContactsOperationCompleted, userState);
        }
        
        private void OnGetContactsOperationCompleted(object arg) {
            if ((this.GetContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactsCompleted(this, new GetContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SMSSiteUserInfo {
        
        private string owner_tx_idField;
        
        private System.DateTime dateCreatedField;
        
        private string ws_tx_idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string emailField;
        
        private string phoneField;
        
        private long cBalanceField;
        
        private UserInfo_settings userSettingsField;
        
        private int activeField;
        
        /// <remarks/>
        public string owner_tx_id {
            get {
                return this.owner_tx_idField;
            }
            set {
                this.owner_tx_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string ws_tx_id {
            get {
                return this.ws_tx_idField;
            }
            set {
                this.ws_tx_idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public long CBalance {
            get {
                return this.cBalanceField;
            }
            set {
                this.cBalanceField = value;
            }
        }
        
        /// <remarks/>
        public UserInfo_settings UserSettings {
            get {
                return this.userSettingsField;
            }
            set {
                this.userSettingsField = value;
            }
        }
        
        /// <remarks/>
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class UserInfo_settings {
        
        private string senderIDField;
        
        private string signatureField;
        
        private string errorEmailField;
        
        private int useSignatureField;
        
        private int timeZoneField;
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorEmail {
            get {
                return this.errorEmailField;
            }
            set {
                this.errorEmailField = value;
            }
        }
        
        /// <remarks/>
        public int UseSignature {
            get {
                return this.useSignatureField;
            }
            set {
                this.useSignatureField = value;
            }
        }
        
        /// <remarks/>
        public int TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class ContactInfo {
        
        private string aliasField;
        
        private string emailField;
        
        private string mobileField;
        
        private string[] groupsField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SentMessageInfo {
        
        private System.DateTime sendEndDateField;
        
        private System.DateTime sendStartDateField;
        
        private long totalSmsField;
        
        private long totalSentField;
        
        private long totalFailedField;
        
        private MessageInfo shortMessageField;
        
        private SendStatusEnum sendStatusField;
        
        private string sendStatusStrField;
        
        private string ownerEmailField;
        
        private string ws_tx_idField;
        
        /// <remarks/>
        public System.DateTime SendEndDate {
            get {
                return this.sendEndDateField;
            }
            set {
                this.sendEndDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendStartDate {
            get {
                return this.sendStartDateField;
            }
            set {
                this.sendStartDateField = value;
            }
        }
        
        /// <remarks/>
        public long TotalSms {
            get {
                return this.totalSmsField;
            }
            set {
                this.totalSmsField = value;
            }
        }
        
        /// <remarks/>
        public long TotalSent {
            get {
                return this.totalSentField;
            }
            set {
                this.totalSentField = value;
            }
        }
        
        /// <remarks/>
        public long TotalFailed {
            get {
                return this.totalFailedField;
            }
            set {
                this.totalFailedField = value;
            }
        }
        
        /// <remarks/>
        public MessageInfo ShortMessage {
            get {
                return this.shortMessageField;
            }
            set {
                this.shortMessageField = value;
            }
        }
        
        /// <remarks/>
        public SendStatusEnum SendStatus {
            get {
                return this.sendStatusField;
            }
            set {
                this.sendStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SendStatusStr {
            get {
                return this.sendStatusStrField;
            }
            set {
                this.sendStatusStrField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerEmail {
            get {
                return this.ownerEmailField;
            }
            set {
                this.ownerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ws_tx_id {
            get {
                return this.ws_tx_idField;
            }
            set {
                this.ws_tx_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class MessageInfo {
        
        private string messageField;
        
        private long messageIDField;
        
        private SMSTypeEnum messageTypeField;
        
        private MessageFolder messageFolderField;
        
        private string callBackField;
        
        private string[] destinationField;
        
        private string deliveryEmailField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public SMSTypeEnum MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public MessageFolder MessageFolder {
            get {
                return this.messageFolderField;
            }
            set {
                this.messageFolderField = value;
            }
        }
        
        /// <remarks/>
        public string CallBack {
            get {
                return this.callBackField;
            }
            set {
                this.callBackField = value;
            }
        }
        
        /// <remarks/>
        public string[] Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryEmail {
            get {
                return this.deliveryEmailField;
            }
            set {
                this.deliveryEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum SMSTypeEnum {
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        FLASH,
        
        /// <remarks/>
        OLOGO,
        
        /// <remarks/>
        RTONE,
        
        /// <remarks/>
        VCARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum MessageFolder {
        
        /// <remarks/>
        SENT_FOLDER,
        
        /// <remarks/>
        SAVED_FOLDER,
        
        /// <remarks/>
        BULK_SENT_FOLDER,
        
        /// <remarks/>
        BULK_SAVED_FOLDER,
        
        /// <remarks/>
        WEBSMS_SENT_FOLDER,
        
        /// <remarks/>
        CUSTOM_SENT_FOLDER,
        
        /// <remarks/>
        BULK_ISSENDING_FOLDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum SendStatusEnum {
        
        /// <remarks/>
        SENT,
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        PAUSED,
        
        /// <remarks/>
        STOPPED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SMSSiteInfo {
        
        private string ws_tx_idField;
        
        private System.DateTime dateCreatedField;
        
        private string ownerEmailField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string prefixField;
        
        private string suffixField;
        
        private string sentUrlField;
        
        private string errorUrlField;
        
        private string sentEmailField;
        
        private string errorEmailField;
        
        private string callbackField;
        
        private bool callbackActiveField;
        
        private System.DateTime callbackExpiryField;
        
        private long cBalanceField;
        
        private int activeField;
        
        private int totalUsersField;
        
        private string remarksField;
        
        private string tag1Field;
        
        private string tag2Field;
        
        private string tag3Field;
        
        /// <remarks/>
        public string ws_tx_id {
            get {
                return this.ws_tx_idField;
            }
            set {
                this.ws_tx_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerEmail {
            get {
                return this.ownerEmailField;
            }
            set {
                this.ownerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string SentUrl {
            get {
                return this.sentUrlField;
            }
            set {
                this.sentUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorUrl {
            get {
                return this.errorUrlField;
            }
            set {
                this.errorUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SentEmail {
            get {
                return this.sentEmailField;
            }
            set {
                this.sentEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorEmail {
            get {
                return this.errorEmailField;
            }
            set {
                this.errorEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Callback {
            get {
                return this.callbackField;
            }
            set {
                this.callbackField = value;
            }
        }
        
        /// <remarks/>
        public bool CallbackActive {
            get {
                return this.callbackActiveField;
            }
            set {
                this.callbackActiveField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CallbackExpiry {
            get {
                return this.callbackExpiryField;
            }
            set {
                this.callbackExpiryField = value;
            }
        }
        
        /// <remarks/>
        public long CBalance {
            get {
                return this.cBalanceField;
            }
            set {
                this.cBalanceField = value;
            }
        }
        
        /// <remarks/>
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public int TotalUsers {
            get {
                return this.totalUsersField;
            }
            set {
                this.totalUsersField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string Tag1 {
            get {
                return this.tag1Field;
            }
            set {
                this.tag1Field = value;
            }
        }
        
        /// <remarks/>
        public string Tag2 {
            get {
                return this.tag2Field;
            }
            set {
                this.tag2Field = value;
            }
        }
        
        /// <remarks/>
        public string Tag3 {
            get {
                return this.tag3Field;
            }
            set {
                this.tag3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class ResponseInfo {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string extraMessageField;
        
        private int totalSuccessField;
        
        private int totalFailureField;
        
        private int totalChargedField;
        
        private long currentBalanceField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ExtraMessage {
            get {
                return this.extraMessageField;
            }
            set {
                this.extraMessageField = value;
            }
        }
        
        /// <remarks/>
        public int TotalSuccess {
            get {
                return this.totalSuccessField;
            }
            set {
                this.totalSuccessField = value;
            }
        }
        
        /// <remarks/>
        public int TotalFailure {
            get {
                return this.totalFailureField;
            }
            set {
                this.totalFailureField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCharged {
            get {
                return this.totalChargedField;
            }
            set {
                this.totalChargedField = value;
            }
        }
        
        /// <remarks/>
        public long CurrentBalance {
            get {
                return this.currentBalanceField;
            }
            set {
                this.currentBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void NewSiteUserCompletedEventHandler(object sender, NewSiteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewSiteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewSiteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateSiteUserCompletedEventHandler(object sender, UpdateSiteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSiteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSiteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DeleteSiteUserCompletedEventHandler(object sender, DeleteSiteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSiteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSiteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAllSiteUsersCompletedEventHandler(object sender, GetAllSiteUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSiteUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSiteUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSSiteUserInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSSiteUserInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void FlashSiteUserCompletedEventHandler(object sender, FlashSiteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlashSiteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FlashSiteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ChangePwdCompletedEventHandler(object sender, ChangePwdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePwdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePwdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void RechargeCompletedEventHandler(object sender, RechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateAccountInfoCompletedEventHandler(object sender, UpdateAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAccountInfoCompletedEventHandler(object sender, GetAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSSiteInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSSiteInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetMessagesCompletedEventHandler(object sender, GetMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SentMessageInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SentMessageInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void InsertContactCompletedEventHandler(object sender, InsertContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateContactCompletedEventHandler(object sender, UpdateContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DeleteContactCompletedEventHandler(object sender, DeleteContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetContactsCompletedEventHandler(object sender, GetContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591