// <auto-generated />
namespace AgentNetworkManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ann8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ann8));
        
        string IMigrationMetadata.Id
        {
            get { return "201610141134385_Ann8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
